repos:
  # Reformatting
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3.9
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
    - id: docformatter
      args: [--in-place]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  -   id: pydocstyle